### ISSUE TITLE
Aktualizacja dla Mautic 5?

### ISSUE THREAD

**Issue by harcesz** [smsapi/smsapi-mautic#3]
Dzięki za udostępnienie wtyczki dla Mautica. Czy można się spodziewać aktualizacji dla jego najnowszej wersji?

**Comment by mpawikowski** [comment]
Dzień dobry,

Nasz dział IT ma na liście zadań weryfikację zgodności naszej wtyczki z Mauticiem 5 i ewentualną niezbędna aktualizację. Na ten moment nie jesteśmy jednak w stanie powiedzieć, kiedy prace zostaną zakończone.

**Comment by harcesz** [comment]
Od razu mogę potwierdzić, że aktualizacja będzie konieczna. Instalacja obecnej nie działa i powoduje krytyczny bład w Mauticu :] W każdym razie z zainteresowaniem czekam, dzięki za udostępnianie oficjalnych wtyczek/integracji!

**Comment by harcesz** [comment]
Konkretny błąd; 

```
PHP Fatal error:  Declaration of MauticPlugin\MauticSmsapiBundle\Integration\SmsapiIntegration::appendToForm(&$builder, $data, $formArea) must be compatible with Mautic\PluginBundle\Integration\AbstractIntegration::appendToForm(&$builder, $data, $formArea): void in /var/www/mautic/plugins/MauticSmsapiBundle/Integration/SmsapiIntegration.php on line 127

In SmsapiIntegration.php line 127:
                                                                                                                                                                                                                  
  Compile Error: Declaration of MauticPlugin\MauticSmsapiBundle\Integration\SmsapiIntegration::appendToForm(&$builder, $data, $formArea) must be compatible with Mautic\PluginBundle\Integration\AbstractIntegra  
  tion::appendToForm(&$builder, $data, $formArea): void          
```                                                                                                                                                 
                                                                                

Wcześniej wspomniane wywalanie całego Mautica jest wynikiem... błędnej nazwy katalogu po rozpakowaniu wtyczki i dotyczy też Mautic v4, nazwa katalogu wtyczki musi brzmieć MauticSmsapiBundle

**Comment by mpawikowski** [comment]
Dziękujemy, przekazałem informację do naszego działu IT.

**Comment by mpawikowski** [comment]
Wtyczka została zaktualizowana dla zapewnienia kompatybilności z Mautic 5.
